name: On push, deploying to Test

on: [push]

jobs:
  run-build-and-deploy:
    uses: octopusden/octopus-base/.github/workflows/common-py-build-deploy.yml@main
    with:
      process_env: Test
      python_versions: "3"
    secrets: inherit

  build-push-docker-image:
    uses: octopusden/octopus-base/.github/workflows/common-docker-build-deploy.yml@main
    with:
      tags: |
        ghcr.io/${{ github.repository }}:${{ github.ref_name }}
